### ISSUE TITLE
VirtualMemoryFiles: New resource proposal

### ISSUE THREAD

**Issue by ChristophHannappel** [dsccommunity/CommonTasks#149]
### Resource proposal

A new composite ressource to configure the system page file via `ComputerManagementDsc\VirtualMemory`.
Configure one or more page files for a system.

I've tried do build one myself, but the build fails with:

> [-] Composite resource folder count matches composite resource count 49ms
> Expected 125, but got 115.
> 114:         $compositeResouces.Count | Should -Be $compositeResouceFolders.Count
> at <ScriptBlock>, C:\Users\HannapCh\Repository\CommonTasks\tests\Unit\DSCResources\DscResources.Tests.ps1: line 114
> 

and when used inside the DSCWorkshop Framework it does not recognise the Composite when building the Mof File.

> "The term 'VirtualMemoryFiles' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the  
spelling of the name, or if a path was included, verify that the path is correct and try again.

Is there an example guide how to add new ones?

### Proposed properties

Property | Type qualifier | Data type | Description | Default value | Allowed values
--- | --- | --- | --- | --- | ---
PropertyName | Key | String | Detailed description | None | None

### Special considerations or limitations

What i've tried:

* Create a folder `VirtualMemoryFiles` at `/source/DSCRessources/`
* Created the files
  * `\source\DSCRessources\VirtualMemoryFiles.schema.psm1`
  * `\source\DSCRessources\VirtualMemoryFiles.psd1`
  * `tests\Unit\DSCResources\Assets\Config\VirtualMemoryFiles.yml`

VirtualMemoryFiles.schema.psm1 contents: 
```powershell
configuration VirtualMemoryFiles
{
    param (
        [Parameter(Mandatory = $true)]
        [hashtable[]]
        $Files
    )

    Import-DscResource -ModuleName ComputerManagementDsc

    foreach ($file in $Files)
    {
        $executionName = $file.Drive
        (Get-DscSplattedResource -ResourceName VirtualMemory -ExecutionName $executionName -Properties $file -NoInvoke).Invoke($file)
    }
}
```
VirtualMemoryFiles.psd1 contents:
```powershell
@{
    RootModule           = 'VirtualMemoryFiles.schema.psm1'

    ModuleVersion        = '0.0.1'

    GUID                 = 'decb37e2-f194-4502-bfee-aed06fafa34d'

    Author               = 'NA'

    CompanyName          = 'NA'

    Copyright            = 'NA'

    DscResourcesToExport = @('VirtualMemoryFiles')
}
```

VirtualMemoryFiles.yml contents:
```yml
Files:
  - Drive: C
  Type: CustomSize
  InitialSize: 4096
  MaximumSize: 4096
  - Drive: P
  Type: CustomSize
  InitialSize: 8192
  MaximumSize: 8192

````

**Comment by ChristophHannappel** [comment]
ok it seams like i've got a faulty windows 10 vm. I'll try a new one and report back

**Comment by raandree** [comment]
I skimmed the code and it looks good to me. If the new configuration does not appear as a valid DSC resource, it is usually due to syntax issues in or inconsistent naming.

If it still doesn't work, can you create a PR so I can run through your code more thoroughly, please?

**Comment by ChristophHannappel** [comment]
The issue had been a bad Windows 10 VM.
